### ISSUE TITLE
issue resolved

### ISSUE THREAD

**Issue by enumer1** [gkpln3/evrit-to-kindle#1]
resolved

**Comment by gkpln3** [comment]
Hey, can you please attach the full log here?
You can upload it as a file

**Comment by enumer1** [comment]
Thank you for the quick response. Where can I find the log file?

**Comment by enumer1** [comment]
@gkpln3 couldn't find it in /var/log

**Comment by gkpln3** [comment]
There is no log file, I meant the full log of the log you sent in the picture

**Comment by enumer1** [comment]
![image](https://user-images.githubusercontent.com/103932892/163829173-3b1e7a1c-d0f5-4e02-89af-67cac0d414f6.png)
ran it after running frida-server (cannot verify that frida server is running for some reason but I assume it is because after executing ./frida-server it freezes, as it should)

**Comment by gkpln3** [comment]
Can you try fetching the orignal (encrypted) epub (using `adb pull`) are see how many `xhtml` files are there?
It's a zip file, you can unpack it using `unzip` or `7z`.

**Comment by gkpln3** [comment]
Yes

**Comment by enumer1** [comment]
@gkpln3 btw I followed "what to do if it breaks" before getting in touch with you - didn't help

**Comment by enumer1** [comment]
@gkpln3 If you want, you can contact me using the email address above for the flow of the discussion

**Comment by gkpln3** [comment]
Here is good.
Maybe try scrolling through the book the its last pages while the frida script is attached.
It may trigger more decryptions.

**Comment by enumer1** [comment]
Just did it. No change

**Comment by enumer1** [comment]
About the "what to do if it breaks", I searched for the string you mentioned there, found the function, its name is a, so I didn't fully understand what the change that I should do in the hook.js file

**Comment by gkpln3** [comment]
There seems to be a problem with the last few pages.
You can try packing the book manually by editing `loader.py`:
goto the line where it says:
```python
tempdir = tempfile.mkdtemp()
```

to say:
```python
tempdir = "archives"
```

**Comment by enumer1** [comment]
no change at all. The change just moves the extraction folder to the same directory and calls it "archives".
Can you clarify the 'what to do if it breaks' please?

**Comment by gkpln3** [comment]
I don't think that the "What to do if it breaks" will hep you here, it was meant to handle situations where the obfuscation is changed, which is not the case here.
You can now try packing the archives inside "archives" directory yourself (again, to a zip archive) and open it as an `epub` book.

**Comment by enumer1** [comment]
There are two things in archives/Books: one is the epub folder, and the other is the epub itself. Tried to open the epub there and it is encrypted. Trying to archive the folder manually now

**Comment by enumer1** [comment]
@gkpln3 I just did it. No change

**Comment by enumer1** [comment]
Hi. Do you have any further suggestions? Are you looking into it?
All the best :)

**Comment by enumer1** [comment]
@gkpln3 finally!!!!!
![image](https://user-images.githubusercontent.com/103932892/164222997-4883e204-f055-4054-a5a1-20660a7835b1.png)
how to get an epub out of the folder that was created?

**Comment by gkpln3** [comment]
Cool!
What did you had to do to get it to work?
The epub should be created automatically.

**Comment by enumer1** [comment]
cannot open the epub that was created for some reason (is the encrypted epub downloaded at the beginning is being dseleted from the tmp directory at the end?)

**Comment by enumer1** [comment]
I gave access permissions to the data/data folder by executing `chmod -R 777`. I think you should add that to the instructions

**Comment by enumer1** [comment]
still nothing with the `.epub` though

**Comment by enumer1** [comment]
Success! thank you so much!

**Comment by gkpln3** [comment]
Great!
Star the repo if you like it :)
