### ISSUE TITLE
Finding cipher methods in newer versions (instructions for updating hook.js no longer relevant)

### ISSUE THREAD

**Issue by multim366** [gkpln3/evrit-to-kindle#5]
It seems like the app structure has changed in latest versions (10.1.6 for instance), and finding the new method that need to be updated in hook.js can not be achieved by following the instructions in the README.
Can you please assist in finding the new method for decryption?

Thanks in advance

**Comment by gkpln3** [comment]
It seems like they've added some root detection method.
The app no longer works on my rooted android phone.
Can you try running it with frida-gadget?

**Comment by multim366** [comment]
But even in previous versions I had to hide root from this app using
Magisk, didn't you need to?

I had trouble adding frida-gadget to the app when I tried before. If you
can help with it somehow (in DM) it would be greatly appreciated.

**Comment by multim366** [comment]
Any update on how to locate the new decryption method in newer versions?

**Comment by gkpln3** [comment]
I've added a root detection bypass, but it also seems like they've made a comprehensive change to the encryption mechanism, I won't be doing this anytime soon, you are welcome to try and update the code.

**Comment by multim366** [comment]
Thank you, I wish I could. However, I don't have the necessary knowledge to solve this.
I hope you get it to at some point, it's such a shame we can't read ebooks we own on whatever devices we use.

This is a great project and thanks a lot for your efforts anyways 🙏
